sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-3.0.6-unix.tar.gz
  - tar -xzf neo4j-community-3.0.6-unix.tar.gz
  - neo4j-community-3.0.6/bin/neo4j start